# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171226_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='\u90ae\u7bb1'),
        ),
    ]
